# Generated by Django 5.1.7 on 2025-03-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.TextField(max_length=100)),
                ('blog_header_img', models.ImageField(upload_to='blog_header_img/')),
                ('blog_body', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BrandDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.TextField(max_length=100)),
                ('brand_logo', models.ImageField(upload_to='brand_logo/')),
                ('brand_strategy_img', models.ImageField(upload_to='brand_strategy_img/')),
            ],
        ),
        migrations.CreateModel(
            name='EmailDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.TextField(max_length=254)),
                ('email_category', models.TextField(max_length=254)),
                ('email_type', models.TextField(max_length=254)),
                ('email_body', models.ImageField(upload_to='email_body/')),
            ],
        ),
    ]
