# Generated by Django 5.1.7 on 2025-03-16 05:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_garage_app', '0002_blogdetails_date_added_blogdetails_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogDetails',
            new_name='BlogDetail',
        ),
        migrations.RenameModel(
            old_name='BrandDetails',
            new_name='BrandDetail',
        ),
        migrations.RenameModel(
            old_name='EmailDetails',
            new_name='EmailDetail',
        ),
    ]
