# Generated by Django 5.1.7 on 2025-03-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_garage_app', '0003_rename_blogdetails_blogdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='blog_body',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='blogdetail',
            name='blog_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='branddetail',
            name='brand_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emaildetail',
            name='email_category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='emaildetail',
            name='email_subject',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='emaildetail',
            name='email_type',
            field=models.CharField(max_length=50),
        ),
    ]
