# Generated by Django 5.1.7 on 2025-03-16 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_garage_app', '0004_alter_blogdetail_blog_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildetail',
            name='connected_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connected_brand', to='email_garage_app.branddetail'),
        ),
    ]
