# Generated by Django 5.1.7 on 2025-03-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_garage_app', '0005_alter_emaildetail_connected_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildetail',
            name='email_body',
            field=models.FileField(upload_to='email_body/'),
        ),
    ]
