# Generated by Django 5.1.7 on 2025-03-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_garage_app', '0006_alter_emaildetail_email_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='branddetail',
            name='brand_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
