# Generated by Django 5.1.7 on 2025-03-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_garage_app', '0008_branddetail_user_templatesdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesdetail',
            name='template_link',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
