# Generated by Django 5.1.7 on 2025-03-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_garage_app', '0009_templatesdetail_template_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='branddetail',
            name='brand_about',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branddetail',
            name='brand_differenciator',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='branddetail',
            name='brand_email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blogdetail',
            name='blog_body',
            field=models.TextField(max_length=10000),
        ),
    ]
