# Generated by Django 5.1.7 on 2025-03-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_garage_app', '0010_branddetail_brand_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branddetail',
            name='brand_url',
            field=models.CharField(default='https://in.pinterest.com/', max_length=100),
            preserve_default=False,
        ),
    ]
