# Generated by Django 5.1.7 on 2025-03-20 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_garage_app', '0011_branddetail_brand_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatesdetail',
            old_name='template_type',
            new_name='template_creation_tool',
        ),
        migrations.RemoveField(
            model_name='templatesdetail',
            name='template_body',
        ),
    ]
