# Generated by Django 5.1.7 on 2025-03-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_garage_app', '0012_rename_template_type_templatesdetail_template_creation_tool_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetail',
            name='blog_header_img',
        ),
        migrations.AlterField(
            model_name='blogdetail',
            name='blog_body',
            field=models.FileField(upload_to='blog_body/'),
        ),
    ]
